#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.10
# In conjunction with Tcl version 8.6
#    Jan 26, 2018 03:14:00 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import wF9_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = BIOS_Automation_Tool (root)
    wF9_support.init(root, top)
    root.mainloop()

w = None
def create_BIOS_Automation_Tool(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = BIOS_Automation_Tool (w)
    wF9_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_BIOS_Automation_Tool():
    global w
    w.destroy()
    w = None


class BIOS_Automation_Tool:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("364x228+1292+1181")
        top.title("BIOS Automation Tool")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")



        self.Text1 = Text(top)
        self.Text1.place(relx=0.58, rely=0.09, relheight=0.75, relwidth=0.37)
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(width=134)
        self.Text1.configure(wrap=WORD)

        self.Msglist = Message(top)
        self.Msglist.place(relx=0.0, rely=0.04, relheight=0.26, relwidth=0.55)
        self.Msglist.configure(background="#d9d9d9")
        self.Msglist.configure(foreground="#000000")
        self.Msglist.configure(highlightbackground="#d9d9d9")
        self.Msglist.configure(highlightcolor="black")
        self.Msglist.configure(text='''Support model list:
HP BL460 G9, BL660 G9''')
        self.Msglist.configure(width=201)

        self.MsgOS = Message(top)
        self.MsgOS.place(relx=0.01, rely=0.35, relheight=0.11, relwidth=0.22)
        self.MsgOS.configure(background="#d9d9d9")
        self.MsgOS.configure(foreground="#000000")
        self.MsgOS.configure(highlightbackground="#d9d9d9")
        self.MsgOS.configure(highlightcolor="black")
        self.MsgOS.configure(text='''OS Version''')
        self.MsgOS.configure(width=70)

        self.MsgSrv = Message(top)
        self.MsgSrv.place(relx=0.03, rely=0.48, relheight=0.2, relwidth=0.24)
        self.MsgSrv.configure(background="#d9d9d9")
        self.MsgSrv.configure(foreground="#000000")
        self.MsgSrv.configure(highlightbackground="#d9d9d9")
        self.MsgSrv.configure(highlightcolor="black")
        self.MsgSrv.configure(text='''Server Name''')
        self.MsgSrv.configure(width=87)

        self.TButton1 = ttk.Button(top)
        self.TButton1.place(relx=0.05, rely=0.7, height=27, width=177)
        self.TButton1.configure(command=wF9_support.click)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Start''')

        self.tCo54 = ttk.Combobox(top)
        self.tCo54.place(relx=0.27, rely=0.35, relheight=0.1, relwidth=0.26)
        self.value_list = ['VSOE','LSOE','WSOE',]
        self.tCo54.configure(values=self.value_list)
        READONLY = 'readonly'
        self.tCo54.configure(state=READONLY)
        self.tCo54.configure(takefocus="")

        self.TEntry1 = ttk.Entry(top)
        self.TEntry1.place(relx=0.27, rely=0.53, relheight=0.1, relwidth=0.26)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="ibeam")

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)








if __name__ == '__main__':
    vp_start_gui()



