#############################################################################
# Generated by PAGE version 4.10
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m38" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor {#000000} 
    wm focusmodel $top passive
    wm geometry $top 364x228+1292+1181
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3722 1894
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "BIOS Automation Tool"
    vTcl:DefineAlias "$top" "topwindow" vTcl:Toplevel:WidgetProc "" 1
    text $top.tex42 \
        -background white -font TkTextFont -foreground black -height 172 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 134 -wrap word 
    .top37.tex42 configure -font TkTextFont
    .top37.tex42 insert end text
    vTcl:DefineAlias "$top.tex42" "Text1" vTcl:WidgetProc "topwindow" 1
    message $top.mes46 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Support model list:
HP BL460 G9, BL660 G9} -width 201 
    vTcl:DefineAlias "$top.mes46" "Msglist" vTcl:WidgetProc "topwindow" 1
    message $top.mes47 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {OS Version} -width 70 
    vTcl:DefineAlias "$top.mes47" "MsgOS" vTcl:WidgetProc "topwindow" 1
    message $top.mes48 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Server Name} -width 87 
    vTcl:DefineAlias "$top.mes48" "MsgSrv" vTcl:WidgetProc "topwindow" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu53 \
        -command click -takefocus {} -text Start 
    vTcl:DefineAlias "$top.tBu53" "TButton1" vTcl:WidgetProc "topwindow" 1
    ttk::combobox $top.tCo54 \
        -values {'VSOE','LSOE','WSOE' {}} -state readonly -foreground {} \
        -background {} -takefocus {} 
    ttk::entry $top.tEn55 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn55" "TEntry1" vTcl:WidgetProc "topwindow" 1
    menu $top.m38 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tex42 \
        -in $top -x 210 -y 20 -width 134 -relwidth 0 -height 172 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes46 \
        -in $top -x 0 -y 10 -width 201 -relwidth 0 -height 59 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes47 \
        -in $top -x 8 -y 80 -width 79 -height 25 -anchor nw \
        -bordermode ignore 
    place $top.mes48 \
        -in $top -x 10 -y 110 -width 87 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu53 \
        -in $top -x 20 -y 160 -width 177 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo54 \
        -in $top -x 103 -y 80 -width 93 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tEn55 \
        -in $top -x 100 -y 120 -width 96 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

  set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

